[package]
name = "runner"
version = "0.1.0"
edition = "2024"
default-run = "runner"

[dependencies]
compression-core = { path = "../compression-core" }
run-length-compression = { path = "../compressors/run-length-compression" }
run-length-channel-compression = { path = "../compressors/run-length-channel-compression"}
huffman-compressor = { path = "../compressors/huffman-compressor" }
image = "0.25.10"
